namespace Knyaz.Optimus.Dom.Css
{
	/// <summary>
	/// https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSS2Properties
	/// </summary>
	public interface ICss2Properties
	{
		string Azimuth { get; set; }
		string Background { get; set; }
		string BackgroundAttachment { get; set; }
		string BackgroundColor { get; set; }
		string BackgroundImage { get; set; }
		string BackgroundPosition { get; set; }
		string BackgroundRepeat { get; set; }
		string Border { get; set; }
		string BorderCollapse { get; set; }
		string BorderColor { get; set; }
		string BorderSpacing { get; set; }
		string BorderStyle { get; set; }
		string BorderTop { get; set; }
		string BorderRight { get; set; }
		string BorderBottom { get; set; }
		string BorderLeft { get; set; }
		string BorderTopColor { get; set; }
		string BorderRightColor { get; set; }
		string BorderBottomColor { get; set; }
		string BorderLeftColor { get; set; }
		string BorderTopStyle { get; set; }
		string BorderRightStyle { get; set; }
		string BorderBottomStyle { get; set; }
		string BorderLeftStyle { get; set; }
		string BorderTopWidth { get; set; }
		string BorderRightWidth { get; set; }
		string BorderBottomWidth { get; set; }
		string BorderLeftWidth { get; set; }
		string BorderWidth { get; set; }
		string Bottom { get; set; }
		string CaptionSide { get; set; }
		string Clear { get; set; }
		string Clip { get; set; }
		string Color { get; set; }
		string Content { get; set; }
		string CounterIncrement { get; set; }
		string CounterReset { get; set; }
		string Cue { get; set; }
		string CueAfter { get; set; }
		string CueBefore { get; set; }
		string Cursor { get; set; }
		string Direction { get; set; }
		string Display { get; set; }
		string Elevation { get; set; }
		string EmptyCells { get; set; }
		string CssFloat { get; set; }
		string Font { get; set; }
		string FontFamily { get; set; }
		string FontSize { get; set; }
		string FontSizeAdjust { get; set; }
		string FontStretch { get; set; }
		string FontStyle { get; set; }
		string FontVariant { get; set; }
		string FontWeight { get; set; }
		string Height { get; set; }
		string Left { get; set; }
		string LetterSpacing { get; set; }
		string LineHeight { get; set; }
		string ListStyle { get; set; }
		string ListStyleImage { get; set; }
		string ListStylePosition { get; set; }
		string ListStyleType { get; set; }
		string Margin { get; set; }
		string MarginTop { get; set; }
		string MarginRight { get; set; }
		string MarginBottom { get; set; }
		string MarginLeft { get; set; }
		string MarkerOffset { get; set; }
		string Marks { get; set; }
		string MaxHeight { get; set; }
		string MaxWidth { get; set; }
		string MinHeight { get; set; }
		string MinWidth { get; set; }
		string Orphans { get; set; }
		string Outline { get; set; }
		string OutlineColor { get; set; }
		string OutlineStyle { get; set; }
		string OutlineWidth { get; set; }
		string Overflow { get; set; }
		string Padding { get; set; }
		string PaddingTop { get; set; }
		string PaddingRight { get; set; }
		string PaddingBottom { get; set; }
		string PaddingLeft { get; set; }
		string Page { get; set; }
		string PageBreakAfter { get; set; }
		string PageBreakBefore { get; set; }
		string PageBreakInside { get; set; }
		string Pause { get; set; }
		string PauseAfter { get; set; }
		string PauseBefore { get; set; }
		string Pitch { get; set; }
		string PitchRange { get; set; }
		string PlayDuring { get; set; }
		string Position { get; set; }
		string Quotes { get; set; }
		string Richness { get; set; }
		string Right { get; set; }
		string Size { get; set; }
		string Speak { get; set; }
		string SpeakHeader { get; set; }
		string SpeakNumeral { get; set; }
		string SpeakPunctuation { get; set; }
		string SpeechRate { get; set; }
		string Stress { get; set; }
		string TableLayout { get; set; }
		string TextAlign { get; set; }
		string TextDecoration { get; set; }
		string TextIndent { get; set; }
		string TextShadow { get; set; }
		string TextTransform { get; set; }
		string Top { get; set; }
		string UnicodeBidi { get; set; }
		string VerticalAlign { get; set; }
		string Visibility { get; set; }
		string VoiceFamily { get; set; }
		string Volume { get; set; }
		string WhiteSpace { get; set; }
		string Widows { get; set; }
		string Width { get; set; }
		string WordSpacing { get; set; }
		string ZIndex { get; set; }

	}
}
