Test("ElementTypesTests", {
    "Node": {run: function(){ Assert.AreEqual("function", typeof Node); }},
    "Element": {run: function(){ Assert.AreEqual("function", typeof Element); }},
    "HTMLBodyElement": {run: function(){ Assert.AreEqual("function", typeof HTMLBodyElement); }},
    "HTMLButtonElement": {run: function(){ Assert.AreEqual("function", typeof HTMLButtonElement); }},
    "HTMLBRElement": {run: function(){ Assert.AreEqual("function", typeof HTMLBRElement); }},
    "HTMLDivElement": {run: function(){ Assert.AreEqual("function", typeof HTMLDivElement); }},
    "HTMLAnchorElement": {run: function(){ Assert.AreEqual("function", typeof HTMLAnchorElement); }},
    "HTMLElement": {run: function(){ Assert.AreEqual("function", typeof HTMLElement); }},
    "HTMLIFrameElement": {run: function(){ Assert.AreEqual("function", typeof HTMLIFrameElement); }},
    "HTMLImageElement": {run: function(){ Assert.AreEqual("function", typeof HTMLImageElement); }},
    "HTMLInputElement": {run: function(){ Assert.AreEqual("function", typeof HTMLInputElement); }},
    "HTMLLabelElement": {run: function(){ Assert.AreEqual("function", typeof HTMLLabelElement); }},
    "HTMLLinkElement": {run: function(){ Assert.AreEqual("function", typeof HTMLLinkElement); }},
    "HTMLTextAreaElement": {run: function(){ Assert.AreEqual("function", typeof HTMLTextAreaElement); }},
    "HTMLUnknownElement": {run: function(){ Assert.AreEqual("function", typeof HTMLUnknownElement); }},
    "HTMLFormElement": {run: function(){ Assert.AreEqual("function", typeof HTMLFormElement); }},
    "HTMLHtmlElement": {run: function(){ Assert.AreEqual("function", typeof HTMLHtmlElement); }},
    "HTMLOptGroupElement": {run: function(){ Assert.AreEqual("function", typeof HTMLOptGroupElement); }},
    "HTMLOptionElement": {run: function(){ Assert.AreEqual("function", typeof HTMLOptionElement); }},
    "HTMLScriptElement": {run: function(){ Assert.AreEqual("function", typeof HTMLScriptElement); }},
    "HTMLSelectElement": {run: function(){ Assert.AreEqual("function", typeof HTMLSelectElement); }},
    "HTMLStyleElement": {run: function(){ Assert.AreEqual("function", typeof HTMLStyleElement); }},
    "HTMLTableElement": {run: function(){ Assert.AreEqual("function", typeof HTMLTableElement); }},
    "HTMLTableRowElement": {run: function(){ Assert.AreEqual("function", typeof HTMLTableRowElement); }},
    "HTMLTableColElement": {run: function(){ Assert.AreEqual("function", typeof HTMLTableColElement); }},
    "HTMLTableCaptionElement": {run: function(){ Assert.AreEqual("function", typeof HTMLTableCaptionElement); }},
    "HTMLTableCellElement": {run: function(){ Assert.AreEqual("function", typeof HTMLTableCellElement); }},
    "HTMLTableSectionElement": {run: function(){ Assert.AreEqual("function", typeof HTMLTableSectionElement); }},
    "Comment": {run: function(){ Assert.AreEqual("function", typeof Comment); }},
    "HTMLDocument": {run: function(){ Assert.AreEqual("function", typeof HTMLDocument); }},
    "Text": {run: function(){ Assert.AreEqual("function", typeof Text); }},
    "Attr": {run: function(){ Assert.AreEqual("function", typeof Attr); }}
});
    