//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var window = this;
        ///
        ///(function (engine) {
        ///	var converters = [];
        ///	converters[&quot;Document&quot;] = wrapDocument;
        ///	converters[&quot;Element&quot;] = wrap;
        ///	converters[&quot;Element[]&quot;] = wrapArray;
        ///	converters[&quot;Node&quot;] = wrap;
        ///	converters[&quot;DocumentFragment&quot;] = wrap;
        ///	converters[&quot;Text&quot;] = wrap;
        ///	converters[&quot;Comment&quot;] = wrap;
        ///	converters[&quot;Event&quot;] = wrapEvent;
        ///	converters[&quot;CssStyleDeclaration&quot;] = wrapStyle;
        ///	
        ///	function bindFunc(target, owner, funcName) {
        ///		var netFuncName = upFirstLetter(funcName);
        ///		var methodInfo = own [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string clrBridge {
            get {
                return ResourceManager.GetString("clrBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v2.1.3
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2014-12-18T15:11Z
        /// */
        ///
        ///(function( global, factory ) {
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///		// For CommonJS and CommonJS-like environments where a proper `window`
        ///		// is present, execute the factory and get jQue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_1_3 {
            get {
                return ResourceManager.GetString("jquery_2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery Form Plugin
        /// * version: 3.51.0-2014.06.20
        /// * Requires jQuery v1.5 or later
        /// * Copyright (c) 2014 M. Alsup
        /// * Examples and documentation at: http://malsup.com/jquery/form/
        /// * Project repository: https://github.com/malsup/form
        /// * Dual licensed under the MIT and GPL licenses.
        /// * https://github.com/malsup/form#copyright-and-license
        /// */
        ////*global ActiveXObject */
        ///
        ///// AMD support
        ///(function (factory) {
        ///	&quot;use strict&quot;;
        ///	if (typeof define === &apos;function&apos; &amp;&amp; define.amd) {
        ///		// using AMD; re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jQuery_Form {
            get {
                return ResourceManager.GetString("jQuery_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Knockout JavaScript library v3.3.0
        /// * (c) Steven Sanderson - http://knockoutjs.com/
        /// * License: MIT (http://www.opensource.org/licenses/mit-license.php)
        /// */
        ///
        ///(function(){
        ///var DEBUG=true;
        ///(function(undefined){
        ///    // (0, eval)(&apos;this&apos;) is a robust way of getting a reference to the global object
        ///    // For details, see http://stackoverflow.com/questions/14119988/return-this-0-evalthis/14120023#14120023
        ///    var window = this || (0, eval)(&apos;this&apos;),
        ///        document = window[&apos;document&apos;],
        ///        navigator = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string knockout {
            get {
                return ResourceManager.GetString("knockout", resourceCulture);
            }
        }
    }
}
