//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var window = this;
        ///
        ///(function (engine) {
        ///	var converters = [];
        ///	
        ///	Object.defineProperty(window, &apos;document&apos;, { get: function () { return engine.Document; } });
        ///	
        ///	function upFirstLetter(string) { return string.charAt(0).toUpperCase() + string.slice(1); }
        ///
        ///	function bindProps(target, owner, propsString) {
        ///		var propsNames = propsString.split(&apos; &apos;);
        ///		for (var i = 0; i &lt; propsNames.length; i++) {
        ///			var names = propsNames[i].split(&apos;:&apos;);
        ///			var jsPropName = names[0];
        ///			var netPropName = names[1] | [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string clrBridge {
            get {
                return ResourceManager.GetString("clrBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v2.1.3
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2014-12-18T15:11Z
        /// */
        ///
        ///(function( global, factory ) {
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///		// For CommonJS and CommonJS-like environments where a proper `window`
        ///		// is present, execute the factory and get jQue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_1_3 {
            get {
                return ResourceManager.GetString("jquery_2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery Form Plugin
        /// * version: 3.51.0-2014.06.20
        /// * Requires jQuery v1.5 or later
        /// * Copyright (c) 2014 M. Alsup
        /// * Examples and documentation at: http://malsup.com/jquery/form/
        /// * Project repository: https://github.com/malsup/form
        /// * Dual licensed under the MIT and GPL licenses.
        /// * https://github.com/malsup/form#copyright-and-license
        /// */
        ////*global ActiveXObject */
        ///
        ///// AMD support
        ///(function (factory) {
        ///	&quot;use strict&quot;;
        ///	if (typeof define === &apos;function&apos; &amp;&amp; define.amd) {
        ///		// using AMD; re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jQuery_Form {
            get {
                return ResourceManager.GetString("jQuery_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Knockout JavaScript library v3.3.0
        /// * (c) Steven Sanderson - http://knockoutjs.com/
        /// * License: MIT (http://www.opensource.org/licenses/mit-license.php)
        /// */
        ///
        ///(function(){
        ///var DEBUG=true;
        ///(function(undefined){
        ///    // (0, eval)(&apos;this&apos;) is a robust way of getting a reference to the global object
        ///    // For details, see http://stackoverflow.com/questions/14119988/return-this-0-evalthis/14120023#14120023
        ///    var window = this || (0, eval)(&apos;this&apos;),
        ///        document = window[&apos;document&apos;],
        ///        navigator = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string knockout {
            get {
                return ResourceManager.GetString("knockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** vim: et:ts=4:sw=4:sts=4
        /// * @license RequireJS 2.1.17 Copyright (c) 2010-2015, The Dojo Foundation All Rights Reserved.
        /// * Available via the MIT or new BSD license.
        /// * see: http://github.com/jrburke/requirejs for details
        /// */
        /////Not using strict: uneven strict support in browsers, #392, and causes
        /////problems with requirejs.exec()/transpiler plugins that may not be strict.
        ////*jslint regexp: true, nomen: true, sloppy: true */
        ////*global window, navigator, document, importScripts, setTimeout, opera */
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string requirejs {
            get {
                return ResourceManager.GetString("requirejs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //https://github.com/rniemeyer/SamplePresentation/blob/master/js/stringTemplateEngine.js
        ///define(function () {
        ///    if (!ko) {
        ///        //when running during optimization build, knockout will not be defined
        ///        return;
        ///    }
        ///
        ///    //define a template source that simply treats the template name as its content
        ///    var templates = {},
        ///		data = {},
        ///		engine = new ko.nativeTemplateEngine();
        ///
        ///    ko.templateSources.stringTemplate = function (template) {
        ///        this.templateName = template;
        ///    };
        ///
        ///    ko.uti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stringTemplateEngine {
            get {
                return ResourceManager.GetString("stringTemplateEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define([&quot;require&quot;, &quot;text&quot;, &quot;stringTemplateEngine&quot;], function (require, text) {
        ///    var loader = {
        ///        load: function (name, req, load, config) {
        ///            var onLoad = config.isBuild ? load : function (content) {
        ///                var tmpDiv = $(&quot;&lt;div&gt;&quot;);
        ///                tmpDiv.html(content);
        ///                var scripts = tmpDiv.find(&quot;script[type=&apos;text/html&apos;]&quot;);
        ///                if (scripts.length &gt; 0) {
        ///                    scripts.each(function (_) {
        ///                        var templateId = $(t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * @license RequireJS text 2.0.10 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
        /// * Available via the MIT or new BSD license.
        /// * see: http://github.com/requirejs/text for details
        /// */
        ////*jslint regexp: true */
        ////*global require, XMLHttpRequest, ActiveXObject,
        ///  define, window, process, Packages,
        ///  java, location, Components, FileUtils */
        ///
        ///define([&apos;module&apos;], function (module) {
        ///    &apos;use strict&apos;;
        ///
        ///    var text, fs, Cc, Ci, xpcIsWindows,
        ///        progIds = [&apos;Msxml2.XMLHTTP&apos;, &apos;Microsoft.XMLH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
    }
}
